# Database.
[database]
[[database.default]]
host = "127.0.0.1"
port = "3306"
user = "rsshub"
pass = "qazxsw"
name = "rsshubdb"
type = "mysql"
debug = "false"
dryrun = 0
weight = "100"
charset = "utf8"
maxIdle = "10"
maxOpen = "100"
maxLifetime = "30s"
# Database logger.
[database.logger]
Path = "/tmp/log/rsshub-auto-refresh/sql"
Level = "all"
Stdout = true


[gfcli]
[[gfcli.gen.dao]]
link   = "mysql:rsshub:qazxsw@tcp(127.0.0.1:3306)/rsshubdb"
group  = ""
prefix = ""
tables = ""
[gfcli.build]
name = "rsshub-auto-refresh"
arch = "amd64"
system = "linux"
mod = "none"
cgo = 0
pack = "config"
version = "v1.0.0"
output = "./bin"
extra = ""

[elasticsearch]
host = "http://127.0.0.1"
port = "9200"
user = "elastic"
pass = "qazxsw"

[refresher]
rsshub-host = "http://localhost:8082"